/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import server.ActTableServer;
import server.LeaseRoomServer;
import server.impl.ActTableServerimpl;
import server.impl.LeaseRoomServerImpl;
import struts.form.ActTableForm;
import entity.ActTable;
import entity.LeaseRoom;
import entity.Users;

 
public class ActTableAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws IOException
	 */
	
	//获得所要举报的房源id
	public ActionForward getRid(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IOException {
		ActTableForm actTableForm = (ActTableForm) form;
		return mapping.findForward("rep");

	}
    //添加举报信息
	public ActionForward addAct(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IOException {
		ActTableForm actTableForm = (ActTableForm) form;
		LeaseRoomServer lserver = new LeaseRoomServerImpl();
		ActTableServer actTableServer = new ActTableServerimpl();
		PrintWriter out = response.getWriter();
		boolean flag = false;
        
		int rid = actTableForm.getRid(); // 所举报的房源id
		LeaseRoom room = lserver.getRoom(rid);// 加载该房源对象
		System.out.println(rid);
		System.out.println(room.getId());
		Users user = (Users) request.getSession().getAttribute("users"); // 获得前当用户
		String act = actTableForm.getType();

		String remark = actTableForm.getRemark(); // 其他举报信息
		if (!remark.equals("")) {
			act += "其他举报信息：" + remark;
		}
		Date date=new Date();
		String time=date.toLocaleString();

		ActTable actTable = new ActTable();
		actTable.setLeaseRoom(room);
		actTable.setUsers(user);
		actTable.setAct(act);
		
		actTable.setTime(time);
		
		actTable.setState(1);
		

		flag = actTableServer.add(actTable);
		if (flag == true) {
			out.print("<script>");
			out.print("alert('举报成功!!!');");
			out.print("window.location='leaseRoom.do?method=getleaseRoom&id="+rid+"';");
			out.print("</script>");
			return null;
		} else {

			out.print("<script>");
			out.print("alert('举报失败!!!');");
			out.print("window.history.go(-1);");
			out.print("</script>");
			return null;

		}

	}
	
	

	
	//删除举报房源
	public ActionForward delAct(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws IOException {
		ActTableForm actTableForm = (ActTableForm) form;
		
		int id=Integer.parseInt(request.getParameter("id"));
		ActTableServer actTableServer=new ActTableServerimpl();
		ActTable actTable=actTableServer.getAct(id);
		
		int rid=Integer.parseInt(request.getParameter("rid"));
		if(actTableServer.delete(actTable)==true)
		{
			//act(mapping, form, request, response);
			
			response.getWriter().print("<script>");
			response.getWriter().print("alert('删除成功！');");
			response.getWriter().print("window.location='actTable.do?method=act&id="+rid+"';");
			response.getWriter().print("</script>");
		}
		else
		{
			//act(mapping, form, request, response);
			
			response.getWriter().print("<script>");
			response.getWriter().print("alert('删除失败！');");
			response.getWriter().print("window.history.back();");
			response.getWriter().print("</script>");
		}
		return null;
	}
	
	
	
	
	//查看举报房源消息
	public ActionForward act(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ActTableForm actTableForm = (ActTableForm) form;
		
		int id=Integer.parseInt(request.getParameter("id"));
		
		
		ActTableServer actTableServer=new ActTableServerimpl();
		
		List<ActTable> list=actTableServer.getactTable(id);
		
		if(list!=null && list.size()>0)
		{
			request.setAttribute("rtitle", list.get(0).getLeaseRoom().getTitle()); //该房源标题
			request.setAttribute("rList",list);
			request.setAttribute("rlid", id);
			request.setAttribute("size", list.size());
		}else{
			LeaseRoomServer server=new LeaseRoomServerImpl();
			LeaseRoom room=server.getRoom(id);
			request.setAttribute("rtitle", room.getTitle());//该房源标题
			request.setAttribute("size", 0);
		}
		
		return mapping.findForward("showLessInfo");
	}
	
	
	
	

}