/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import entity.Admin;

import server.AdminServer;
import server.impl.AdminServerImpl;
import struts.form.AdminForm;
import struts.form.UsersForm;

/**
 * MyEclipse Struts Creation date: 06-22-2010
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/admin" name="adminForm" input="/form/admin.jsp"
 *                parameter="method" scope="request" validate="true"
 */
public class AdminAction extends DispatchAction {

	public ActionForward adminLogin(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IOException {
		PrintWriter out = response.getWriter();
		AdminForm adminForm = (AdminForm) form;// TODO Auto-generated method
		// stub
		AdminServer server = new AdminServerImpl();

		Admin admin = server.loginAdmin(adminForm.getAname());

		if (admin == null) {
			out.print("<script>");
			out.print("alert('该管理员不存在');");
			out.print("window.history.go(-1);");
			out.print("</script>");
			return null;
		}
		if (!admin.getApwd().equals(adminForm.getApwd())) {
			out.print("<script>");
			out.print("alert('密码不正确');");
			out.print("window.history.go(-1);");
			out.print("</script>");
			return null;

		}
		request.getSession().setAttribute("admin", admin);
		out.print("<script>");
		out.print("window.location='htindex.jsp'");
		out.print("</script>");

		return null;
	}

	public ActionForward addAdmin(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IOException {
		PrintWriter out = response.getWriter();
		AdminForm adminForm = (AdminForm) form;// TODO Auto-generated method
		boolean falg = false;
		Admin admin = new Admin();
		admin.setAname(adminForm.getAname());
		admin.setApwd(adminForm.getApwd());
		admin.setState(1);
		AdminServer adServer = new AdminServerImpl();
		falg = adServer.insertAdmin(admin);
		if (falg = true) {

			out.print("<script>");
			out.print("alert('添加成功!!!');");
			out.print("window.location='AddAdmin.jsp';");

			out.print("</script>");
			return null;
		} else {

			out.print("<script>");
			out.print("alert('添加失败!!!');");
			out.print("window.location='AddAdmin.jsp';");
			out.print("</script>");
			return null;
		}

	}

	public ActionForward delAdmin(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IOException {
		AdminForm adminForm = (AdminForm) form;

		int id = Integer.parseInt(request.getParameter("id"));
		AdminServer server = new AdminServerImpl();
		server.deleteAdmin(id);
		return SelectAdmin(mapping, form, request, response);

	}

	public ActionForward SelectAdmin(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IOException {
		AdminForm adminForm = (AdminForm) form;
		AdminServer server = new AdminServerImpl();
		List<Admin> alist = server.select();
		request.setAttribute("alist", alist);

		return mapping.findForward("look");
	}

	// 退出
	public ActionForward logout(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IOException {
		AdminForm adminForm = (AdminForm) form;
		request.getSession().setAttribute("admin", null);

		return mapping.findForward("login");

	}
}