/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import java.lang.reflect.InvocationTargetException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import entity.AreaType;
import entity.HouseType;
import server.AreaTypeServer;
import server.HouseTypeServer;
import server.impl.AreaTypeServerImpl;
import server.impl.HouseTypeServerimpl;
import struts.form.AreaTypeForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-21-2010
 * 
 * XDoclet definition:
 * @struts.action path="/areaType" name="areaTypeForm" input="/areaType.jsp" parameter="method" scope="request" validate="true"
 */
public class AreaTypeAction extends DispatchAction {
	private static final Object AreaTypeForm = null;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward addArea(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AreaTypeForm areaTypeForm = (AreaTypeForm) form;// TODO Auto-generated method stub
	
		AreaType areaType=new AreaType();
		areaType.setArea(areaTypeForm.getArea());
		areaType.setState(1);

		AreaTypeServer areaTypeServer=new AreaTypeServerImpl();
		areaTypeServer.addArea(areaType);
		
		return selectArea(mapping, form, request, response);
	}
	public ActionForward deleteArea(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AreaTypeForm areaTypeForm = (AreaTypeForm) form;// TODO Auto-generated method stub
		
		int id=Integer.parseInt(request.getParameter("id"));
		AreaTypeServer areaTypeServer=new AreaTypeServerImpl();
		areaTypeServer.delArea(areaTypeServer.getthis(id));
		return selectArea(mapping, form, request, response);
	}
	public ActionForward selectArea(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AreaTypeForm areaTypeForm = (AreaTypeForm) form;// TODO Auto-generated method stub
		
		AreaTypeServer areaTypeServer=new AreaTypeServerImpl();
		List<AreaType> list=areaTypeServer.selArea();
		request.setAttribute("alist", list);
		return mapping.findForward("ok");
	}
	public ActionForward selArea(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AreaTypeForm areaTypeForm = (AreaTypeForm) form;// TODO Auto-generated method stub
		AreaTypeServer areaTypeServer=new AreaTypeServerImpl();
		List<AreaType> list=areaTypeServer.selArea();
		request.setAttribute("alist", list);
		return mapping.findForward("isnu");
	}
  
}