package entity;

import java.util.Date;

/**
 * BegRent generated by MyEclipse Persistence Tools
 */

public class BegRent implements java.io.Serializable {

	// Fields

	private Integer id;
	
	private Users users;
	private AreaType areaType;
	private HouseType houseType;
	private String address;
	private int minprice;
	private int maxprice;
	private String minarceage;
	private String maxarceage;
	private String time;
	private Integer chamber;
	private Integer hall;
	private Integer toilet;
	private String remark;
	private Integer state;
	private String esthment;

	// Constructors

	/** default constructor */
	public BegRent() {
	}

	/** minimal constructor */




	/** full constructor */




	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public AreaType getAreaType() {
		return this.areaType;
	}

	public void setAreaType(AreaType areaType) {
		this.areaType = areaType;
	}

	public HouseType getHouseType() {
		return this.houseType;
	}

	public void setHouseType(HouseType houseType) {
		this.houseType = houseType;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	





	public int getMinprice() {
		return minprice;
	}

	public void setMinprice(int minprice) {
		this.minprice = minprice;
	}

	public int getMaxprice() {
		return maxprice;
	}

	public void setMaxprice(int maxprice) {
		this.maxprice = maxprice;
	}

	public String getMinarceage() {
		return minarceage;
	}

	public void setMinarceage(String minarceage) {
		this.minarceage = minarceage;
	}

	public String getMaxarceage() {
		return maxarceage;
	}

	public void setMaxarceage(String maxarceage) {
		this.maxarceage = maxarceage;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public String getEsthment() {
		return this.esthment;
	}

	public void setEsthment(String esthment) {
		this.esthment = esthment;
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public Integer getChamber() {
		return chamber;
	}

	public void setChamber(Integer chamber) {
		this.chamber = chamber;
	}

	public Integer getHall() {
		return hall;
	}

	public void setHall(Integer hall) {
		this.hall = hall;
	}

	public Integer getToilet() {
		return toilet;
	}

	public void setToilet(Integer toilet) {
		this.toilet = toilet;
	}



}