package entity;

import java.util.Date;

/**
 * ChooseRoom generated by MyEclipse Persistence Tools
 */

public class ChooseRoom implements java.io.Serializable {

	// Fields

	private Integer id;
	private Users users;
	private LeaseRoom leaseRoom;
	private String time;
	private Integer state;

	// Constructors

	/** default constructor */
	public ChooseRoom() {
	}

	// Property accessors

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public LeaseRoom getLeaseRoom() {
		return this.leaseRoom;
	}

	public void setLeaseRoom(LeaseRoom leaseRoom) {
		this.leaseRoom = leaseRoom;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

}