package entity;

/**
 * ImageTable generated by MyEclipse Persistence Tools
 */

public class ImageTable implements java.io.Serializable {

	// Fields

	private Integer id;
	private LeaseRoom leaseRoom;
	private String image;

	// Constructors

	/** default constructor */
	public ImageTable() {
	}

	/** minimal constructor */
	public ImageTable(LeaseRoom leaseRoom) {
		this.leaseRoom = leaseRoom;
	}

	/** full constructor */
	public ImageTable(LeaseRoom leaseRoom, String image) {
		this.leaseRoom = leaseRoom;
		this.image = image;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public LeaseRoom getLeaseRoom() {
		return this.leaseRoom;
	}

	public void setLeaseRoom(LeaseRoom leaseRoom) {
		this.leaseRoom = leaseRoom;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}