package entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LeaseRoom generated by MyEclipse Persistence Tools
 */

public class LeaseRoom implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer chamber;
	private Integer hall;
	private Integer toilet;
	private Users users;
	private AreaType areaType;
	private HouseType houseType;
	private String address;
	private String time;
	private Float acreage;
	private String title;
	private Float pirce;
	private String esthment;
	private String img;
	private String remark;
	private Integer state;

	// Constructors

	/** default constructor */
	public LeaseRoom() {
	}

	/** minimal constructor */

	/** full constructor */

	// Property accessors
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public AreaType getAreaType() {
		return this.areaType;
	}

	public void setAreaType(AreaType areaType) {
		this.areaType = areaType;
	}

	public HouseType getHouseType() {
		return this.houseType;
	}

	public void setHouseType(HouseType houseType) {
		this.houseType = houseType;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getChamber() {
		return chamber;
	}

	public void setChamber(int chamber) {
		this.chamber = chamber;
	}

	public int getHall() {
		return hall;
	}

	public void setHall(int hall) {
		this.hall = hall;
	}

	public int getToilet() {
		return toilet;
	}

	public void setToilet(int toilet) {
		this.toilet = toilet;
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Float getAcreage() {
		return acreage;
	}

	public void setAcreage(Float acreage) {
		this.acreage = acreage;
	}

	public Float getPirce() {
		return pirce;
	}

	public void setPirce(Float pirce) {
		this.pirce = pirce;
	}

	public String getEsthment() {
		return esthment;
	}

	public void setEsthment(String esthment) {
		this.esthment = esthment;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public void setChamber(Integer chamber) {
		this.chamber = chamber;
	}

	public void setHall(Integer hall) {
		this.hall = hall;
	}

	public void setToilet(Integer toilet) {
		this.toilet = toilet;
	}

	public String getImg() {
		return img;
	}

	public void setImg(String img) {
		this.img = img;
	}

}