package entity;

import java.util.HashSet;
import java.util.Set;

/**
 * RoomType generated by MyEclipse Persistence Tools
 */

public class RoomType implements java.io.Serializable {

	// Fields

	private Integer id;
	private String chamber;
	private String hall;
	private String toilet;
	private Integer state;
	
	// Constructors

	/** default constructor */
	public RoomType() {
	}

	/** minimal constructor */
	public RoomType(String chamber, String hall, String toilet, Integer state) {
		this.chamber = chamber;
		this.hall = hall;
		this.toilet = toilet;
		this.state = state;
	}

	/** full constructor */
	public RoomType(String chamber, String hall, String toilet, Integer state,
			Set leaseRooms) {
		this.chamber = chamber;
		this.hall = hall;
		this.toilet = toilet;
		this.state = state;
		 
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getChamber() {
		return this.chamber;
	}

	public void setChamber(String chamber) {
		this.chamber = chamber;
	}

	public String getHall() {
		return this.hall;
	}

	public void setHall(String hall) {
		this.hall = hall;
	}

	public String getToilet() {
		return this.toilet;
	}

	public void setToilet(String toilet) {
		this.toilet = toilet;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

 
}