/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-23-2010
 * 
 * XDoclet definition:
 * @struts.form name="begRentForm"
 */
public class BegRentForm extends ActionForm {
	/*
	 * Generated fields
	 */
	private String[] esthment;

	/** time property */
	private String time;
	private int showPage;
	/** arceage property */
	private String minarceage;
	private String maxarceage;

	/** price property */
	private int minprice;
	
	private int maxprice;

	/** address property */
	private String address;

	/** uid property */
	private Integer uid;

	/** aid property */
	private Integer aid;

	/** state property */
	private Integer state;

	/** remark property */
	private String remark;

	/** hid property */
	private Integer hid;

	/** id property */
	private Integer id;

	private int chamber;
	private int hall;
	private int toilet;
	/*
	 * Generated Methods
	 */

	public int getChamber() {
		return chamber;
	}

	public void setChamber(int chamber) {
		this.chamber = chamber;
	}

	public int getHall() {
		return hall;
	}

	public void setHall(int hall) {
		this.hall = hall;
	}

	public int getToilet() {
		return toilet;
	}

	public void setToilet(int toilet) {
		this.toilet = toilet;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the time.
	 * @return String
	 */
	public String getTime() {
		return time;
	}

	/** 
	 * Set the time.
	 * @param time The time to set
	 */
	public void setTime(String time) {
		this.time = time;
	}

	/** 
	 * Returns the arceage.
	 * @return String
	 */


	/** 
	 * Set the arceage.
	 * @param arceage The arceage to set
	 */

	/** 
	 * Returns the price.
	 * @return String
	 */

	/** 
	 * Set the price.
	 * @param price The price to set
	 */

	/** 
	 * Returns the address.
	 * @return String
	 */
	public String getAddress() {
		return address;
	}

	/** 
	 * Set the address.
	 * @param address The address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/** 
	 * Returns the uid.
	 * @return Integer
	 */
	public Integer getUid() {
		return uid;
	}

	/** 
	 * Set the uid.
	 * @param uid The uid to set
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/** 
	 * Returns the aid.
	 * @return Integer
	 */
	public Integer getAid() {
		return aid;
	}

	/** 
	 * Set the aid.
	 * @param aid The aid to set
	 */
	public void setAid(Integer aid) {
		this.aid = aid;
	}

	/** 
	 * Returns the state.
	 * @return Integer
	 */
	public Integer getState() {
		return state;
	}

	/** 
	 * Set the state.
	 * @param state The state to set
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/** 
	 * Returns the remark.
	 * @return String
	 */
	public String getRemark() {
		return remark;
	}

	/** 
	 * Set the remark.
	 * @param remark The remark to set
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/** 
	 * Returns the hid.
	 * @return Integer
	 */
	public Integer getHid() {
		return hid;
	}

	/** 
	 * Set the hid.
	 * @param hid The hid to set
	 */
	public void setHid(Integer hid) {
		this.hid = hid;
	}

	/** 
	 * Returns the id.
	 * @return Integer
	 */
	public Integer getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}



	public String[] getEsthment() {
		return esthment;
	}

	public void setEsthment(String[] esthment) {
		this.esthment = esthment;
	}

	public String getMinarceage() {
		return minarceage;
	}

	public void setMinarceage(String minarceage) {
		this.minarceage = minarceage;
	}

	public String getMaxarceage() {
		return maxarceage;
	}

	public void setMaxarceage(String maxarceage) {
		this.maxarceage = maxarceage;
	}



	public int getMinprice() {
		return minprice;
	}

	public void setMinprice(int minprice) {
		this.minprice = minprice;
	}

	public int getMaxprice() {
		return maxprice;
	}

	public void setMaxprice(int maxprice) {
		this.maxprice = maxprice;
	}

	public int getShowPage() {
		return showPage;
	}

	public void setShowPage(int showPage) {
		this.showPage = showPage;
	}


}